// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BseTask.proto

package com.xinqihd.sns.gameserver.proto;

public final class XinqiBseTask {
  private XinqiBseTask() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AwardOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string id = 1;
    boolean hasId();
    String getId();
    
    // optional string type = 2 [default = "item"];
    boolean hasType();
    String getType();
    
    // optional int32 lv = 3;
    boolean hasLv();
    int getLv();
    
    // optional int32 sex = 4;
    boolean hasSex();
    int getSex();
    
    // optional int32 count = 5;
    boolean hasCount();
    int getCount();
    
    // optional int32 indate = 6;
    boolean hasIndate();
    int getIndate();
  }
  public static final class Award extends
      com.google.protobuf.GeneratedMessage
      implements AwardOrBuilder {
    // Use Award.newBuilder() to construct.
    private Award(Builder builder) {
      super(builder);
    }
    private Award(boolean noInit) {}
    
    private static final Award defaultInstance;
    public static Award getDefaultInstance() {
      return defaultInstance;
    }
    
    public Award getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_Award_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_Award_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string type = 2 [default = "item"];
    public static final int TYPE_FIELD_NUMBER = 2;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 lv = 3;
    public static final int LV_FIELD_NUMBER = 3;
    private int lv_;
    public boolean hasLv() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getLv() {
      return lv_;
    }
    
    // optional int32 sex = 4;
    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getSex() {
      return sex_;
    }
    
    // optional int32 count = 5;
    public static final int COUNT_FIELD_NUMBER = 5;
    private int count_;
    public boolean hasCount() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getCount() {
      return count_;
    }
    
    // optional int32 indate = 6;
    public static final int INDATE_FIELD_NUMBER = 6;
    private int indate_;
    public boolean hasIndate() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getIndate() {
      return indate_;
    }
    
    private void initFields() {
      id_ = "";
      type_ = "item";
      lv_ = 0;
      sex_ = 0;
      count_ = 0;
      indate_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, lv_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, count_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, indate_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, lv_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, sex_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, count_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, indate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBseTask.AwardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_Award_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_Award_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "item";
        bitField0_ = (bitField0_ & ~0x00000002);
        lv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        sex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        indate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award build() {
        com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award result = new com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lv_ = lv_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.indate_ = indate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLv()) {
          setLv(other.getLv());
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasIndate()) {
          setIndate(other.getIndate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              type_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lv_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sex_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              count_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              indate_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string type = 2 [default = "item"];
      private java.lang.Object type_ = "item";
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
      }
      
      // optional int32 lv = 3;
      private int lv_ ;
      public boolean hasLv() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getLv() {
        return lv_;
      }
      public Builder setLv(int value) {
        bitField0_ |= 0x00000004;
        lv_ = value;
        onChanged();
        return this;
      }
      public Builder clearLv() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lv_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 sex = 4;
      private int sex_ ;
      public boolean hasSex() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getSex() {
        return sex_;
      }
      public Builder setSex(int value) {
        bitField0_ |= 0x00000008;
        sex_ = value;
        onChanged();
        return this;
      }
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 count = 5;
      private int count_ ;
      public boolean hasCount() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getCount() {
        return count_;
      }
      public Builder setCount(int value) {
        bitField0_ |= 0x00000010;
        count_ = value;
        onChanged();
        return this;
      }
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        count_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 indate = 6;
      private int indate_ ;
      public boolean hasIndate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getIndate() {
        return indate_;
      }
      public Builder setIndate(int value) {
        bitField0_ |= 0x00000020;
        indate_ = value;
        onChanged();
        return this;
      }
      public Builder clearIndate() {
        bitField0_ = (bitField0_ & ~0x00000020);
        indate_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.Award)
    }
    
    static {
      defaultInstance = new Award(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.Award)
  }
  
  public interface TaskDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // optional string name = 2;
    boolean hasName();
    String getName();
    
    // optional string desc = 3;
    boolean hasDesc();
    String getDesc();
    
    // optional string taskTarget = 4;
    boolean hasTaskTarget();
    String getTaskTarget();
    
    // optional int32 step = 5;
    boolean hasStep();
    int getStep();
    
    // optional int32 level = 6;
    boolean hasLevel();
    int getLevel();
    
    // optional string type = 7;
    boolean hasType();
    String getType();
    
    // optional int32 exp = 8;
    boolean hasExp();
    int getExp();
    
    // optional int32 gold = 9;
    boolean hasGold();
    int getGold();
    
    // optional int32 ticket = 10;
    boolean hasTicket();
    int getTicket();
    
    // optional int32 gongxun = 11;
    boolean hasGongxun();
    int getGongxun();
    
    // optional int32 caifu = 12;
    boolean hasCaifu();
    int getCaifu();
    
    // optional int32 guildwealth = 13;
    boolean hasGuildwealth();
    int getGuildwealth();
    
    // optional int32 guildcredit = 14;
    boolean hasGuildcredit();
    int getGuildcredit();
    
    // repeated .com.xinqihd.sns.gameserver.proto.Award awards = 15;
    java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award> 
        getAwardsList();
    com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award getAwards(int index);
    int getAwardsCount();
    java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseTask.AwardOrBuilder> 
        getAwardsOrBuilderList();
    com.xinqihd.sns.gameserver.proto.XinqiBseTask.AwardOrBuilder getAwardsOrBuilder(
        int index);
  }
  public static final class TaskData extends
      com.google.protobuf.GeneratedMessage
      implements TaskDataOrBuilder {
    // Use TaskData.newBuilder() to construct.
    private TaskData(Builder builder) {
      super(builder);
    }
    private TaskData(boolean noInit) {}
    
    private static final TaskData defaultInstance;
    public static TaskData getDefaultInstance() {
      return defaultInstance;
    }
    
    public TaskData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_TaskData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_TaskData_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string desc = 3;
    public static final int DESC_FIELD_NUMBER = 3;
    private java.lang.Object desc_;
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDesc() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          desc_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string taskTarget = 4;
    public static final int TASKTARGET_FIELD_NUMBER = 4;
    private java.lang.Object taskTarget_;
    public boolean hasTaskTarget() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getTaskTarget() {
      java.lang.Object ref = taskTarget_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          taskTarget_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTaskTargetBytes() {
      java.lang.Object ref = taskTarget_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        taskTarget_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 step = 5;
    public static final int STEP_FIELD_NUMBER = 5;
    private int step_;
    public boolean hasStep() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getStep() {
      return step_;
    }
    
    // optional int32 level = 6;
    public static final int LEVEL_FIELD_NUMBER = 6;
    private int level_;
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getLevel() {
      return level_;
    }
    
    // optional string type = 7;
    public static final int TYPE_FIELD_NUMBER = 7;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 exp = 8;
    public static final int EXP_FIELD_NUMBER = 8;
    private int exp_;
    public boolean hasExp() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getExp() {
      return exp_;
    }
    
    // optional int32 gold = 9;
    public static final int GOLD_FIELD_NUMBER = 9;
    private int gold_;
    public boolean hasGold() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public int getGold() {
      return gold_;
    }
    
    // optional int32 ticket = 10;
    public static final int TICKET_FIELD_NUMBER = 10;
    private int ticket_;
    public boolean hasTicket() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getTicket() {
      return ticket_;
    }
    
    // optional int32 gongxun = 11;
    public static final int GONGXUN_FIELD_NUMBER = 11;
    private int gongxun_;
    public boolean hasGongxun() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getGongxun() {
      return gongxun_;
    }
    
    // optional int32 caifu = 12;
    public static final int CAIFU_FIELD_NUMBER = 12;
    private int caifu_;
    public boolean hasCaifu() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public int getCaifu() {
      return caifu_;
    }
    
    // optional int32 guildwealth = 13;
    public static final int GUILDWEALTH_FIELD_NUMBER = 13;
    private int guildwealth_;
    public boolean hasGuildwealth() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public int getGuildwealth() {
      return guildwealth_;
    }
    
    // optional int32 guildcredit = 14;
    public static final int GUILDCREDIT_FIELD_NUMBER = 14;
    private int guildcredit_;
    public boolean hasGuildcredit() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    public int getGuildcredit() {
      return guildcredit_;
    }
    
    // repeated .com.xinqihd.sns.gameserver.proto.Award awards = 15;
    public static final int AWARDS_FIELD_NUMBER = 15;
    private java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award> awards_;
    public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award> getAwardsList() {
      return awards_;
    }
    public java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseTask.AwardOrBuilder> 
        getAwardsOrBuilderList() {
      return awards_;
    }
    public int getAwardsCount() {
      return awards_.size();
    }
    public com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award getAwards(int index) {
      return awards_.get(index);
    }
    public com.xinqihd.sns.gameserver.proto.XinqiBseTask.AwardOrBuilder getAwardsOrBuilder(
        int index) {
      return awards_.get(index);
    }
    
    private void initFields() {
      id_ = "";
      name_ = "";
      desc_ = "";
      taskTarget_ = "";
      step_ = 0;
      level_ = 0;
      type_ = "";
      exp_ = 0;
      gold_ = 0;
      ticket_ = 0;
      gongxun_ = 0;
      caifu_ = 0;
      guildwealth_ = 0;
      guildcredit_ = 0;
      awards_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTaskTargetBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, step_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTypeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, exp_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, gold_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, ticket_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, gongxun_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, caifu_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, guildwealth_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, guildcredit_);
      }
      for (int i = 0; i < awards_.size(); i++) {
        output.writeMessage(15, awards_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTaskTargetBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, step_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, level_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTypeBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, exp_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, gold_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, ticket_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, gongxun_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, caifu_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, guildwealth_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, guildcredit_);
      }
      for (int i = 0; i < awards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, awards_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_TaskData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_TaskData_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAwardsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        desc_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        taskTarget_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        step_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        exp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        gold_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        ticket_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        gongxun_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        caifu_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        guildwealth_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        guildcredit_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        if (awardsBuilder_ == null) {
          awards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00004000);
        } else {
          awardsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData build() {
        com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData result = new com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.desc_ = desc_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.taskTarget_ = taskTarget_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.step_ = step_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.exp_ = exp_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.gold_ = gold_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.ticket_ = ticket_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.gongxun_ = gongxun_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.caifu_ = caifu_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.guildwealth_ = guildwealth_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.guildcredit_ = guildcredit_;
        if (awardsBuilder_ == null) {
          if (((bitField0_ & 0x00004000) == 0x00004000)) {
            awards_ = java.util.Collections.unmodifiableList(awards_);
            bitField0_ = (bitField0_ & ~0x00004000);
          }
          result.awards_ = awards_;
        } else {
          result.awards_ = awardsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDesc()) {
          setDesc(other.getDesc());
        }
        if (other.hasTaskTarget()) {
          setTaskTarget(other.getTaskTarget());
        }
        if (other.hasStep()) {
          setStep(other.getStep());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        if (other.hasGold()) {
          setGold(other.getGold());
        }
        if (other.hasTicket()) {
          setTicket(other.getTicket());
        }
        if (other.hasGongxun()) {
          setGongxun(other.getGongxun());
        }
        if (other.hasCaifu()) {
          setCaifu(other.getCaifu());
        }
        if (other.hasGuildwealth()) {
          setGuildwealth(other.getGuildwealth());
        }
        if (other.hasGuildcredit()) {
          setGuildcredit(other.getGuildcredit());
        }
        if (awardsBuilder_ == null) {
          if (!other.awards_.isEmpty()) {
            if (awards_.isEmpty()) {
              awards_ = other.awards_;
              bitField0_ = (bitField0_ & ~0x00004000);
            } else {
              ensureAwardsIsMutable();
              awards_.addAll(other.awards_);
            }
            onChanged();
          }
        } else {
          if (!other.awards_.isEmpty()) {
            if (awardsBuilder_.isEmpty()) {
              awardsBuilder_.dispose();
              awardsBuilder_ = null;
              awards_ = other.awards_;
              bitField0_ = (bitField0_ & ~0x00004000);
              awardsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAwardsFieldBuilder() : null;
            } else {
              awardsBuilder_.addAllMessages(other.awards_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              desc_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              taskTarget_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              step_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              level_ = input.readInt32();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              type_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              exp_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              gold_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              ticket_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              gongxun_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              caifu_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              guildwealth_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              guildcredit_ = input.readInt32();
              break;
            }
            case 122: {
              com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder subBuilder = com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAwards(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string name = 2;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // optional string desc = 3;
      private java.lang.Object desc_ = "";
      public boolean hasDesc() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDesc() {
        java.lang.Object ref = desc_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          desc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDesc(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
        return this;
      }
      public Builder clearDesc() {
        bitField0_ = (bitField0_ & ~0x00000004);
        desc_ = getDefaultInstance().getDesc();
        onChanged();
        return this;
      }
      void setDesc(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        desc_ = value;
        onChanged();
      }
      
      // optional string taskTarget = 4;
      private java.lang.Object taskTarget_ = "";
      public boolean hasTaskTarget() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getTaskTarget() {
        java.lang.Object ref = taskTarget_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          taskTarget_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTaskTarget(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        taskTarget_ = value;
        onChanged();
        return this;
      }
      public Builder clearTaskTarget() {
        bitField0_ = (bitField0_ & ~0x00000008);
        taskTarget_ = getDefaultInstance().getTaskTarget();
        onChanged();
        return this;
      }
      void setTaskTarget(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        taskTarget_ = value;
        onChanged();
      }
      
      // optional int32 step = 5;
      private int step_ ;
      public boolean hasStep() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getStep() {
        return step_;
      }
      public Builder setStep(int value) {
        bitField0_ |= 0x00000010;
        step_ = value;
        onChanged();
        return this;
      }
      public Builder clearStep() {
        bitField0_ = (bitField0_ & ~0x00000010);
        step_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 level = 6;
      private int level_ ;
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getLevel() {
        return level_;
      }
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000020;
        level_ = value;
        onChanged();
        return this;
      }
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000020);
        level_ = 0;
        onChanged();
        return this;
      }
      
      // optional string type = 7;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        type_ = value;
        onChanged();
      }
      
      // optional int32 exp = 8;
      private int exp_ ;
      public boolean hasExp() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getExp() {
        return exp_;
      }
      public Builder setExp(int value) {
        bitField0_ |= 0x00000080;
        exp_ = value;
        onChanged();
        return this;
      }
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000080);
        exp_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 gold = 9;
      private int gold_ ;
      public boolean hasGold() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public int getGold() {
        return gold_;
      }
      public Builder setGold(int value) {
        bitField0_ |= 0x00000100;
        gold_ = value;
        onChanged();
        return this;
      }
      public Builder clearGold() {
        bitField0_ = (bitField0_ & ~0x00000100);
        gold_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 ticket = 10;
      private int ticket_ ;
      public boolean hasTicket() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public int getTicket() {
        return ticket_;
      }
      public Builder setTicket(int value) {
        bitField0_ |= 0x00000200;
        ticket_ = value;
        onChanged();
        return this;
      }
      public Builder clearTicket() {
        bitField0_ = (bitField0_ & ~0x00000200);
        ticket_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 gongxun = 11;
      private int gongxun_ ;
      public boolean hasGongxun() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getGongxun() {
        return gongxun_;
      }
      public Builder setGongxun(int value) {
        bitField0_ |= 0x00000400;
        gongxun_ = value;
        onChanged();
        return this;
      }
      public Builder clearGongxun() {
        bitField0_ = (bitField0_ & ~0x00000400);
        gongxun_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 caifu = 12;
      private int caifu_ ;
      public boolean hasCaifu() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public int getCaifu() {
        return caifu_;
      }
      public Builder setCaifu(int value) {
        bitField0_ |= 0x00000800;
        caifu_ = value;
        onChanged();
        return this;
      }
      public Builder clearCaifu() {
        bitField0_ = (bitField0_ & ~0x00000800);
        caifu_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 guildwealth = 13;
      private int guildwealth_ ;
      public boolean hasGuildwealth() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public int getGuildwealth() {
        return guildwealth_;
      }
      public Builder setGuildwealth(int value) {
        bitField0_ |= 0x00001000;
        guildwealth_ = value;
        onChanged();
        return this;
      }
      public Builder clearGuildwealth() {
        bitField0_ = (bitField0_ & ~0x00001000);
        guildwealth_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 guildcredit = 14;
      private int guildcredit_ ;
      public boolean hasGuildcredit() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public int getGuildcredit() {
        return guildcredit_;
      }
      public Builder setGuildcredit(int value) {
        bitField0_ |= 0x00002000;
        guildcredit_ = value;
        onChanged();
        return this;
      }
      public Builder clearGuildcredit() {
        bitField0_ = (bitField0_ & ~0x00002000);
        guildcredit_ = 0;
        onChanged();
        return this;
      }
      
      // repeated .com.xinqihd.sns.gameserver.proto.Award awards = 15;
      private java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award> awards_ =
        java.util.Collections.emptyList();
      private void ensureAwardsIsMutable() {
        if (!((bitField0_ & 0x00004000) == 0x00004000)) {
          awards_ = new java.util.ArrayList<com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award>(awards_);
          bitField0_ |= 0x00004000;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award, com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseTask.AwardOrBuilder> awardsBuilder_;
      
      public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award> getAwardsList() {
        if (awardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(awards_);
        } else {
          return awardsBuilder_.getMessageList();
        }
      }
      public int getAwardsCount() {
        if (awardsBuilder_ == null) {
          return awards_.size();
        } else {
          return awardsBuilder_.getCount();
        }
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award getAwards(int index) {
        if (awardsBuilder_ == null) {
          return awards_.get(index);
        } else {
          return awardsBuilder_.getMessage(index);
        }
      }
      public Builder setAwards(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award value) {
        if (awardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAwardsIsMutable();
          awards_.set(index, value);
          onChanged();
        } else {
          awardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAwards(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder builderForValue) {
        if (awardsBuilder_ == null) {
          ensureAwardsIsMutable();
          awards_.set(index, builderForValue.build());
          onChanged();
        } else {
          awardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAwards(com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award value) {
        if (awardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAwardsIsMutable();
          awards_.add(value);
          onChanged();
        } else {
          awardsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAwards(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award value) {
        if (awardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAwardsIsMutable();
          awards_.add(index, value);
          onChanged();
        } else {
          awardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAwards(
          com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder builderForValue) {
        if (awardsBuilder_ == null) {
          ensureAwardsIsMutable();
          awards_.add(builderForValue.build());
          onChanged();
        } else {
          awardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAwards(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder builderForValue) {
        if (awardsBuilder_ == null) {
          ensureAwardsIsMutable();
          awards_.add(index, builderForValue.build());
          onChanged();
        } else {
          awardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAwards(
          java.lang.Iterable<? extends com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award> values) {
        if (awardsBuilder_ == null) {
          ensureAwardsIsMutable();
          super.addAll(values, awards_);
          onChanged();
        } else {
          awardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAwards() {
        if (awardsBuilder_ == null) {
          awards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00004000);
          onChanged();
        } else {
          awardsBuilder_.clear();
        }
        return this;
      }
      public Builder removeAwards(int index) {
        if (awardsBuilder_ == null) {
          ensureAwardsIsMutable();
          awards_.remove(index);
          onChanged();
        } else {
          awardsBuilder_.remove(index);
        }
        return this;
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder getAwardsBuilder(
          int index) {
        return getAwardsFieldBuilder().getBuilder(index);
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.AwardOrBuilder getAwardsOrBuilder(
          int index) {
        if (awardsBuilder_ == null) {
          return awards_.get(index);  } else {
          return awardsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseTask.AwardOrBuilder> 
           getAwardsOrBuilderList() {
        if (awardsBuilder_ != null) {
          return awardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(awards_);
        }
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder addAwardsBuilder() {
        return getAwardsFieldBuilder().addBuilder(
            com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.getDefaultInstance());
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder addAwardsBuilder(
          int index) {
        return getAwardsFieldBuilder().addBuilder(
            index, com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.getDefaultInstance());
      }
      public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder> 
           getAwardsBuilderList() {
        return getAwardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award, com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseTask.AwardOrBuilder> 
          getAwardsFieldBuilder() {
        if (awardsBuilder_ == null) {
          awardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award, com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseTask.AwardOrBuilder>(
                  awards_,
                  ((bitField0_ & 0x00004000) == 0x00004000),
                  getParentForChildren(),
                  isClean());
          awards_ = null;
        }
        return awardsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.TaskData)
    }
    
    static {
      defaultInstance = new TaskData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.TaskData)
  }
  
  public interface BseTaskOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .com.xinqihd.sns.gameserver.proto.TaskData tasks = 1;
    java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData> 
        getTasksList();
    com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData getTasks(int index);
    int getTasksCount();
    java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskDataOrBuilder> 
        getTasksOrBuilderList();
    com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskDataOrBuilder getTasksOrBuilder(
        int index);
  }
  public static final class BseTask extends
      com.google.protobuf.GeneratedMessage
      implements BseTaskOrBuilder {
    // Use BseTask.newBuilder() to construct.
    private BseTask(Builder builder) {
      super(builder);
    }
    private BseTask(boolean noInit) {}
    
    private static final BseTask defaultInstance;
    public static BseTask getDefaultInstance() {
      return defaultInstance;
    }
    
    public BseTask getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_BseTask_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_BseTask_fieldAccessorTable;
    }
    
    // repeated .com.xinqihd.sns.gameserver.proto.TaskData tasks = 1;
    public static final int TASKS_FIELD_NUMBER = 1;
    private java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData> tasks_;
    public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData> getTasksList() {
      return tasks_;
    }
    public java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskDataOrBuilder> 
        getTasksOrBuilderList() {
      return tasks_;
    }
    public int getTasksCount() {
      return tasks_.size();
    }
    public com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData getTasks(int index) {
      return tasks_.get(index);
    }
    public com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskDataOrBuilder getTasksOrBuilder(
        int index) {
      return tasks_.get(index);
    }
    
    private void initFields() {
      tasks_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getTasksCount(); i++) {
        if (!getTasks(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < tasks_.size(); i++) {
        output.writeMessage(1, tasks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < tasks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tasks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_BseTask_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.internal_static_com_xinqihd_sns_gameserver_proto_BseTask_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTasksFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (tasksBuilder_ == null) {
          tasks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          tasksBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask build() {
        com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask result = new com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask(this);
        int from_bitField0_ = bitField0_;
        if (tasksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            tasks_ = java.util.Collections.unmodifiableList(tasks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tasks_ = tasks_;
        } else {
          result.tasks_ = tasksBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask.getDefaultInstance()) return this;
        if (tasksBuilder_ == null) {
          if (!other.tasks_.isEmpty()) {
            if (tasks_.isEmpty()) {
              tasks_ = other.tasks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTasksIsMutable();
              tasks_.addAll(other.tasks_);
            }
            onChanged();
          }
        } else {
          if (!other.tasks_.isEmpty()) {
            if (tasksBuilder_.isEmpty()) {
              tasksBuilder_.dispose();
              tasksBuilder_ = null;
              tasks_ = other.tasks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tasksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTasksFieldBuilder() : null;
            } else {
              tasksBuilder_.addAllMessages(other.tasks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getTasksCount(); i++) {
          if (!getTasks(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder subBuilder = com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTasks(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .com.xinqihd.sns.gameserver.proto.TaskData tasks = 1;
      private java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData> tasks_ =
        java.util.Collections.emptyList();
      private void ensureTasksIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          tasks_ = new java.util.ArrayList<com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData>(tasks_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskDataOrBuilder> tasksBuilder_;
      
      public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData> getTasksList() {
        if (tasksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tasks_);
        } else {
          return tasksBuilder_.getMessageList();
        }
      }
      public int getTasksCount() {
        if (tasksBuilder_ == null) {
          return tasks_.size();
        } else {
          return tasksBuilder_.getCount();
        }
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData getTasks(int index) {
        if (tasksBuilder_ == null) {
          return tasks_.get(index);
        } else {
          return tasksBuilder_.getMessage(index);
        }
      }
      public Builder setTasks(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData value) {
        if (tasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTasksIsMutable();
          tasks_.set(index, value);
          onChanged();
        } else {
          tasksBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setTasks(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder builderForValue) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.set(index, builderForValue.build());
          onChanged();
        } else {
          tasksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addTasks(com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData value) {
        if (tasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTasksIsMutable();
          tasks_.add(value);
          onChanged();
        } else {
          tasksBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addTasks(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData value) {
        if (tasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTasksIsMutable();
          tasks_.add(index, value);
          onChanged();
        } else {
          tasksBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addTasks(
          com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder builderForValue) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.add(builderForValue.build());
          onChanged();
        } else {
          tasksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addTasks(
          int index, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder builderForValue) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.add(index, builderForValue.build());
          onChanged();
        } else {
          tasksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllTasks(
          java.lang.Iterable<? extends com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData> values) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          super.addAll(values, tasks_);
          onChanged();
        } else {
          tasksBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearTasks() {
        if (tasksBuilder_ == null) {
          tasks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tasksBuilder_.clear();
        }
        return this;
      }
      public Builder removeTasks(int index) {
        if (tasksBuilder_ == null) {
          ensureTasksIsMutable();
          tasks_.remove(index);
          onChanged();
        } else {
          tasksBuilder_.remove(index);
        }
        return this;
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder getTasksBuilder(
          int index) {
        return getTasksFieldBuilder().getBuilder(index);
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskDataOrBuilder getTasksOrBuilder(
          int index) {
        if (tasksBuilder_ == null) {
          return tasks_.get(index);  } else {
          return tasksBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskDataOrBuilder> 
           getTasksOrBuilderList() {
        if (tasksBuilder_ != null) {
          return tasksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tasks_);
        }
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder addTasksBuilder() {
        return getTasksFieldBuilder().addBuilder(
            com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.getDefaultInstance());
      }
      public com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder addTasksBuilder(
          int index) {
        return getTasksFieldBuilder().addBuilder(
            index, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.getDefaultInstance());
      }
      public java.util.List<com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder> 
           getTasksBuilderList() {
        return getTasksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskDataOrBuilder> 
          getTasksFieldBuilder() {
        if (tasksBuilder_ == null) {
          tasksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder, com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskDataOrBuilder>(
                  tasks_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          tasks_ = null;
        }
        return tasksBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.BseTask)
    }
    
    static {
      defaultInstance = new BseTask(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.BseTask)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_Award_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_Award_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_TaskData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_TaskData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_BseTask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_BseTask_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rBseTask.proto\022 com.xinqihd.sns.gameser" +
      "ver.proto\"_\n\005Award\022\n\n\002id\030\001 \001(\t\022\022\n\004type\030\002" +
      " \001(\t:\004item\022\n\n\002lv\030\003 \001(\005\022\013\n\003sex\030\004 \001(\005\022\r\n\005c" +
      "ount\030\005 \001(\005\022\016\n\006indate\030\006 \001(\005\"\237\002\n\010TaskData\022" +
      "\n\n\002id\030\001 \002(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004desc\030\003 \001(\t\022" +
      "\022\n\ntaskTarget\030\004 \001(\t\022\014\n\004step\030\005 \001(\005\022\r\n\005lev" +
      "el\030\006 \001(\005\022\014\n\004type\030\007 \001(\t\022\013\n\003exp\030\010 \001(\005\022\014\n\004g" +
      "old\030\t \001(\005\022\016\n\006ticket\030\n \001(\005\022\017\n\007gongxun\030\013 \001" +
      "(\005\022\r\n\005caifu\030\014 \001(\005\022\023\n\013guildwealth\030\r \001(\005\022\023" +
      "\n\013guildcredit\030\016 \001(\005\0227\n\006awards\030\017 \003(\0132\'.co",
      "m.xinqihd.sns.gameserver.proto.Award\"D\n\007" +
      "BseTask\0229\n\005tasks\030\001 \003(\0132*.com.xinqihd.sns" +
      ".gameserver.proto.TaskDataB\016B\014XinqiBseTa" +
      "sk"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xinqihd_sns_gameserver_proto_Award_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xinqihd_sns_gameserver_proto_Award_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_Award_descriptor,
              new java.lang.String[] { "Id", "Type", "Lv", "Sex", "Count", "Indate", },
              com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.class,
              com.xinqihd.sns.gameserver.proto.XinqiBseTask.Award.Builder.class);
          internal_static_com_xinqihd_sns_gameserver_proto_TaskData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_xinqihd_sns_gameserver_proto_TaskData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_TaskData_descriptor,
              new java.lang.String[] { "Id", "Name", "Desc", "TaskTarget", "Step", "Level", "Type", "Exp", "Gold", "Ticket", "Gongxun", "Caifu", "Guildwealth", "Guildcredit", "Awards", },
              com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.class,
              com.xinqihd.sns.gameserver.proto.XinqiBseTask.TaskData.Builder.class);
          internal_static_com_xinqihd_sns_gameserver_proto_BseTask_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_xinqihd_sns_gameserver_proto_BseTask_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_BseTask_descriptor,
              new java.lang.String[] { "Tasks", },
              com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask.class,
              com.xinqihd.sns.gameserver.proto.XinqiBseTask.BseTask.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
